### ISSUE TITLE
SDK Version 2.2.0: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by felixhagspiel** [Mangopay/mangopay2-java-sdk#112]
Hello,

we are getting a lot of connection resets on the Sandbox API.
The error occurs often, but when we send the same request multiple times it works at some point (after 3-6 tries).
Note that the error does not happen on the Production API, only on Sandbox. Server & Firewall Setup is exactly the same for Sandbox and Production. We are using Version 2.2.0 (maven) of the Java SDK.

What could be the cause of this problem?
I can also provide you with a wireshark dump if you wish.

Full error:

```
15:44:35,794 ERROR [stderr] (default task-4) java.net.SocketException: Connection reset
15:44:35,795 ERROR [stderr] (default task-4) 	at java.net.SocketInputStream.read(SocketInputStream.java:210)
15:44:35,796 ERROR [stderr] (default task-4) 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
15:44:35,796 ERROR [stderr] (default task-4) 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
15:44:35,796 ERROR [stderr] (default task-4) 	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
15:44:35,796 ERROR [stderr] (default task-4) 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
15:44:35,796 ERROR [stderr] (default task-4) 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
15:44:35,797 ERROR [stderr] (default task-4) 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
15:44:35,797 ERROR [stderr] (default task-4) 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
15:44:35,797 ERROR [stderr] (default task-4) 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
15:44:35,797 ERROR [stderr] (default task-4) 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
15:44:35,798 ERROR [stderr] (default task-4) 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
15:44:35,798 ERROR [stderr] (default task-4) 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
15:44:35,798 ERROR [stderr] (default task-4) 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
15:44:35,798 ERROR [stderr] (default task-4) 	at com.mangopay.core.RestTool.doRequest(RestTool.java:383)
15:44:35,799 ERROR [stderr] (default task-4) 	at com.mangopay.core.RestTool.request(RestTool.java:142)
15:44:35,799 ERROR [stderr] (default task-4) 	at com.mangopay.core.RestTool.request(RestTool.java:186)
15:44:35,799 ERROR [stderr] (default task-4) 	at com.mangopay.core.APIs.implementation.OAuthApiImpl.createToken(OAuthApiImpl.java:55)
15:44:35,799 ERROR [stderr] (default task-4) 	at com.mangopay.core.AuthorizationTokenManager.getToken(AuthorizationTokenManager.java:39)
15:44:35,799 ERROR [stderr] (default task-4) 	at com.mangopay.core.AuthenticationHelper.getHttpHeaderStrong(AuthenticationHelper.java:61)
15:44:35,800 ERROR [stderr] (default task-4) 	at com.mangopay.core.AuthenticationHelper.getHttpHeaderKey(AuthenticationHelper.java:30)
15:44:35,800 ERROR [stderr] (default task-4) 	at com.mangopay.core.RestTool.getHttpHeaders(RestTool.java:1014)
15:44:35,800 ERROR [stderr] (default task-4) 	at com.mangopay.core.RestTool.doRequest(RestTool.java:336)
15:44:35,800 ERROR [stderr] (default task-4) 	at com.mangopay.core.RestTool.request(RestTool.java:142)
15:44:35,800 ERROR [stderr] (default task-4) 	at com.mangopay.core.APIs.ApiBase.createObject(ApiBase.java:221)
15:44:35,801 ERROR [stderr] (default task-4) 	at com.mangopay.core.APIs.ApiBase.createObject(ApiBase.java:239)
15:44:35,801 ERROR [stderr] (default task-4) 	at com.mangopay.core.APIs.implementation.UserApiImpl.createBankAccount(UserApiImpl.java:98)
15:44:35,801 ERROR [stderr] (default task-4) 	at com.mangopay.core.APIs.implementation.UserApiImpl.createBankAccount(UserApiImpl.java:92)
15:44:35,801 ERROR [stderr] (default task-4) 	at de.plx.boundary.PaymentBoundary.createPaymentBankaccount(PaymentBoundary.java:263)
15:44:35,801 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:44:35,802 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:44:35,802 ERROR [stderr] (default task-4) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:44:35,802 ERROR [stderr] (default task-4) 	at java.lang.reflect.Method.invoke(Method.java:498)
15:44:35,802 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
15:44:35,802 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,803 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)
15:44:35,803 ERROR [stderr] (default task-4) 	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:82)
15:44:35,803 ERROR [stderr] (default task-4) 	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:93)
15:44:35,803 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
15:44:35,804 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,804 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
15:44:35,804 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,804 ERROR [stderr] (default task-4) 	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
15:44:35,804 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,805 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)
15:44:35,805 ERROR [stderr] (default task-4) 	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
15:44:35,805 ERROR [stderr] (default task-4) 	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:83)
15:44:35,805 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,806 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
15:44:35,806 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,806 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)
15:44:35,806 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,806 ERROR [stderr] (default task-4) 	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
15:44:35,807 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
15:44:35,807 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,807 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
15:44:35,807 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,807 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:254)
15:44:35,808 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:329)
15:44:35,808 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:239)
15:44:35,808 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,808 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
15:44:35,809 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,815 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47)
15:44:35,816 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,816 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)
15:44:35,816 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,816 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22)
15:44:35,817 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,817 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
15:44:35,817 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,817 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67)
15:44:35,817 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,818 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
15:44:35,818 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,818 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)
15:44:35,818 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,819 ERROR [stderr] (default task-4) 	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:64)
15:44:35,819 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,819 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:356)
15:44:35,819 ERROR [stderr] (default task-4) 	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:636)
15:44:35,819 ERROR [stderr] (default task-4) 	at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:61)
15:44:35,820 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,820 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:356)
15:44:35,820 ERROR [stderr] (default task-4) 	at org.jboss.invocation.PrivilegedWithCombinerInterceptor.processInvocation(PrivilegedWithCombinerInterceptor.java:80)
15:44:35,820 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,820 ERROR [stderr] (default task-4) 	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
15:44:35,821 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198)
15:44:35,821 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:185)
15:44:35,821 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,821 ERROR [stderr] (default task-4) 	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
15:44:35,822 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:73)
15:44:35,822 ERROR [stderr] (default task-4) 	at de.plx.boundary.PaymentBoundary$$$view7.createPaymentBankaccount(Unknown Source)
15:44:35,822 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:44:35,822 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:44:35,823 ERROR [stderr] (default task-4) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:44:35,823 ERROR [stderr] (default task-4) 	at java.lang.reflect.Method.invoke(Method.java:498)
15:44:35,823 ERROR [stderr] (default task-4) 	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:433)
15:44:35,823 ERROR [stderr] (default task-4) 	at org.jboss.weld.bean.proxy.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:128)
15:44:35,823 ERROR [stderr] (default task-4) 	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
15:44:35,824 ERROR [stderr] (default task-4) 	at org.jboss.weld.bean.proxy.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:67)
15:44:35,824 ERROR [stderr] (default task-4) 	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
15:44:35,824 ERROR [stderr] (default task-4) 	at de.plx.boundary.PaymentBoundary$Proxy$_$$_Weld$EnterpriseProxy$.createPaymentBankaccount(Unknown Source)
15:44:35,824 ERROR [stderr] (default task-4) 	at de.plx.boundary.UserBoundary.createUserBankAccountDetails(UserBoundary.java:749)
15:44:35,824 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:44:35,825 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:44:35,825 ERROR [stderr] (default task-4) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:44:35,825 ERROR [stderr] (default task-4) 	at java.lang.reflect.Method.invoke(Method.java:498)
15:44:35,825 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
15:44:35,826 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,826 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)
15:44:35,826 ERROR [stderr] (default task-4) 	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:82)
15:44:35,826 ERROR [stderr] (default task-4) 	at org.jboss.as.weld.ejb.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:93)
15:44:35,826 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
15:44:35,827 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,827 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
15:44:35,827 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,827 ERROR [stderr] (default task-4) 	at org.jboss.as.jpa.interceptor.SBInvocationInterceptor.processInvocation(SBInvocationInterceptor.java:47)
15:44:35,828 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,828 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:437)
15:44:35,828 ERROR [stderr] (default task-4) 	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
15:44:35,828 ERROR [stderr] (default task-4) 	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:83)
15:44:35,828 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,829 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
15:44:35,829 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,829 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21)
15:44:35,829 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,829 ERROR [stderr] (default task-4) 	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
15:44:35,830 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
15:44:35,830 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,830 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.pool.PooledInstanceInterceptor.processInvocation(PooledInstanceInterceptor.java:51)
15:44:35,830 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,830 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:275)
15:44:35,831 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:327)
15:44:35,831 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:239)
15:44:35,831 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,831 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
15:44:35,831 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,832 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47)
15:44:35,832 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,832 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)
15:44:35,832 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,833 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22)
15:44:35,833 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,833 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
15:44:35,833 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,833 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67)
15:44:35,834 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,834 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
15:44:35,834 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,834 ERROR [stderr] (default task-4) 	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54)
15:44:35,834 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,835 ERROR [stderr] (default task-4) 	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:64)
15:44:35,835 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,835 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:356)
15:44:35,835 ERROR [stderr] (default task-4) 	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:636)
15:44:35,835 ERROR [stderr] (default task-4) 	at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:61)
15:44:35,836 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,836 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:356)
15:44:35,836 ERROR [stderr] (default task-4) 	at org.jboss.invocation.PrivilegedWithCombinerInterceptor.processInvocation(PrivilegedWithCombinerInterceptor.java:80)
15:44:35,836 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,836 ERROR [stderr] (default task-4) 	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
15:44:35,837 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198)
15:44:35,837 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:185)
15:44:35,837 ERROR [stderr] (default task-4) 	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
15:44:35,837 ERROR [stderr] (default task-4) 	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
15:44:35,837 ERROR [stderr] (default task-4) 	at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:73)
15:44:35,838 ERROR [stderr] (default task-4) 	at de.plx.boundary.UserBoundary$$$view2.createUserBankAccountDetails(Unknown Source)
15:44:35,838 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:44:35,838 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:44:35,838 ERROR [stderr] (default task-4) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:44:35,838 ERROR [stderr] (default task-4) 	at java.lang.reflect.Method.invoke(Method.java:498)
15:44:35,839 ERROR [stderr] (default task-4) 	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:433)
15:44:35,839 ERROR [stderr] (default task-4) 	at org.jboss.weld.bean.proxy.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:128)
15:44:35,839 ERROR [stderr] (default task-4) 	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56)
15:44:35,839 ERROR [stderr] (default task-4) 	at org.jboss.weld.bean.proxy.InjectionPointPropagatingEnterpriseTargetBeanInstance.invoke(InjectionPointPropagatingEnterpriseTargetBeanInstance.java:67)
15:44:35,839 ERROR [stderr] (default task-4) 	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
15:44:35,840 ERROR [stderr] (default task-4) 	at de.plx.boundary.UserBoundary$Proxy$_$$_Weld$EnterpriseProxy$.createUserBankAccountDetails(Unknown Source)
15:44:35,840 ERROR [stderr] (default task-4) 	at de.plx.web.adapter.UserAdapter.usersBankAccount(UserAdapter.java:125)
15:44:35,840 ERROR [stderr] (default task-4) 	at de.plx.web.adapter.UserAdapter$Proxy$_$$_WeldSubclass.usersBankAccount$$super(Unknown Source)
15:44:35,840 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:44:35,840 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:44:35,841 ERROR [stderr] (default task-4) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:44:35,841 ERROR [stderr] (default task-4) 	at java.lang.reflect.Method.invoke(Method.java:498)
15:44:35,841 ERROR [stderr] (default task-4) 	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:49)
15:44:35,841 ERROR [stderr] (default task-4) 	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
15:44:35,841 ERROR [stderr] (default task-4) 	at de.plx.security.UserRegisteredAndActiveChecker.checkUserFullyRegistered(UserRegisteredAndActiveChecker.java:74)
15:44:35,841 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:44:35,842 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:44:35,842 ERROR [stderr] (default task-4) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:44:35,842 ERROR [stderr] (default task-4) 	at java.lang.reflect.Method.invoke(Method.java:498)
15:44:35,842 ERROR [stderr] (default task-4) 	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:74)
15:44:35,842 ERROR [stderr] (default task-4) 	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
15:44:35,842 ERROR [stderr] (default task-4) 	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
15:44:35,843 ERROR [stderr] (default task-4) 	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
15:44:35,843 ERROR [stderr] (default task-4) 	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
15:44:35,843 ERROR [stderr] (default task-4) 	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
15:44:35,843 ERROR [stderr] (default task-4) 	at de.plx.web.adapter.UserAdapter$Proxy$_$$_WeldSubclass.usersBankAccount(Unknown Source)
15:44:35,843 ERROR [stderr] (default task-4) 	at de.plx.web.adapter.UserAdapter$Proxy$_$$_WeldClientProxy.usersBankAccount(Unknown Source)
15:44:35,844 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:44:35,844 ERROR [stderr] (default task-4) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:44:35,844 ERROR [stderr] (default task-4) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:44:35,844 ERROR [stderr] (default task-4) 	at java.lang.reflect.Method.invoke(Method.java:498)
15:44:35,844 ERROR [stderr] (default task-4) 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
15:44:35,845 ERROR [stderr] (default task-4) 	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
15:44:35,845 ERROR [stderr] (default task-4) 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
15:44:35,845 ERROR [stderr] (default task-4) 	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
15:44:35,845 ERROR [stderr] (default task-4) 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
15:44:35,845 ERROR [stderr] (default task-4) 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
15:44:35,845 ERROR [stderr] (default task-4) 	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
15:44:35,846 ERROR [stderr] (default task-4) 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
15:44:35,846 ERROR [stderr] (default task-4) 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
15:44:35,846 ERROR [stderr] (default task-4) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
15:44:35,846 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
15:44:35,846 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
15:44:35,846 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
15:44:35,847 ERROR [stderr] (default task-4) 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
15:44:35,847 ERROR [stderr] (default task-4) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
15:44:35,847 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
15:44:35,847 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
15:44:35,847 ERROR [stderr] (default task-4) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
15:44:35,847 ERROR [stderr] (default task-4) 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
15:44:35,848 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
15:44:35,848 ERROR [stderr] (default task-4) 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
15:44:35,848 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
15:44:35,848 ERROR [stderr] (default task-4) 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
15:44:35,848 ERROR [stderr] (default task-4) 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
15:44:35,848 ERROR [stderr] (default task-4) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
15:44:35,849 ERROR [stderr] (default task-4) 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
15:44:35,849 ERROR [stderr] (default task-4) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
15:44:35,849 ERROR [stderr] (default task-4) 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
15:44:35,849 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
15:44:35,849 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
15:44:35,849 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
15:44:35,850 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
15:44:35,850 ERROR [stderr] (default task-4) 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
15:44:35,850 ERROR [stderr] (default task-4) 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
15:44:35,850 ERROR [stderr] (default task-4) 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
15:44:35,850 ERROR [stderr] (default task-4) 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
15:44:35,850 ERROR [stderr] (default task-4) 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
15:44:35,851 ERROR [stderr] (default task-4) 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
15:44:35,851 ERROR [stderr] (default task-4) 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
15:44:35,851 ERROR [stderr] (default task-4) 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
15:44:35,851 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
15:44:35,851 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
15:44:35,852 ERROR [stderr] (default task-4) 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
15:44:35,852 ERROR [stderr] (default task-4) 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
15:44:35,852 ERROR [stderr] (default task-4) 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
15:44:35,852 ERROR [stderr] (default task-4) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:44:35,852 ERROR [stderr] (default task-4) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:44:35,852 ERROR [stderr] (default task-4) 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mickaelpois** [comment]
Hello @felixhagspiel 

Thanks for your feedback.
From when are these issues happening in Sandbox env. ?
We have released a new Sandbox API version this afternoon, which makes this env. unstable for a short time.

Mickaël

**Comment by felixhagspiel** [comment]
Hey @mickaelpois, thanks for the fast reply!
The errors are occuring for some time now (roughly 1 month). So I dont think that the release of the new version is causing these problems. 

But if you release a new version today, I can wait until its deployed and see if the errors still occur with the new Sandbox API.

**Comment by felixhagspiel** [comment]
We just tested, and unfortunately the error still occurs. How should we proceed to find the reason of the error?
